language: node_js

matrix:
  include:
    - node_js: 4
    - node_js: 5
    - node_js: 6
    - node_js: 7
    - node_js: 8
  allow_failures:
    - node_js: 5
    - node_js: 7
  fast_finish: true

after_success:
  - cat ./test-results/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
